spring:
  application:
    name: account
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: C##ACCOUNT_DB
    password: bankapp123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      # hibernate.dialect: org.hibernate.dialect.Oracle19cDialect  # Uncomment if needed

server:
  port: 9010
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true